// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEs-MfuG3no7sLvG_tJvRK8BFQs63huz4',
    appId: '1:121147775704:ios:457aa756fb2b25ca37d5ad',
    messagingSenderId: '121147775704',
    projectId: 'guardianwatch-4c902',
    storageBucket: 'guardianwatch-4c902.firebasestorage.app',
    iosClientId: '121147775704-dop1111am0ha7he64gp0vadh89s52v3p.apps.googleusercontent.com',
    iosBundleId: 'com.circum.guardianwatch',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkpLrLJRTgFUR3b1EgWq_PL_BSYZZo1pk',
    appId: '1:121147775704:web:76b968b9ef57c1b937d5ad',
    messagingSenderId: '121147775704',
    projectId: 'guardianwatch-4c902',
    authDomain: 'guardianwatch-4c902.firebaseapp.com',
    storageBucket: 'guardianwatch-4c902.firebasestorage.app',
    measurementId: 'G-NHL3CGJD3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-RhvsKyMauqha_GqFQDuvCPBPcEQx-JU',
    appId: '1:121147775704:android:d5934b3b44aeb1c237d5ad',
    messagingSenderId: '121147775704',
    projectId: 'guardianwatch-4c902',
    storageBucket: 'guardianwatch-4c902.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkpLrLJRTgFUR3b1EgWq_PL_BSYZZo1pk',
    appId: '1:121147775704:web:30ce01499dd38b5d37d5ad',
    messagingSenderId: '121147775704',
    projectId: 'guardianwatch-4c902',
    authDomain: 'guardianwatch-4c902.firebaseapp.com',
    storageBucket: 'guardianwatch-4c902.firebasestorage.app',
    measurementId: 'G-SJSGWKGN96',
  );

}