// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkWhDOmLXmGzWdqegxjMuv3ZDUYmY3spM',
    appId: '1:19497292943:web:b8e5a4fb881267b8edccfa',
    messagingSenderId: '19497292943',
    projectId: 'guardianwatch-b1972',
    authDomain: 'guardianwatch-b1972.firebaseapp.com',
    storageBucket: 'guardianwatch-b1972.firebasestorage.app',
    measurementId: 'G-NLMCMR3MDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHQNixJ7HtclWAhnDrIoTyyLeYeLDLOPM',
    appId: '1:19497292943:android:331f5754cf0f3b40edccfa',
    messagingSenderId: '19497292943',
    projectId: 'guardianwatch-b1972',
    storageBucket: 'guardianwatch-b1972.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSD5Dl2CbWvyaY2cZISSwEAouoFNn9bJI',
    appId: '1:19497292943:ios:741b21190bd9b6bbedccfa',
    messagingSenderId: '19497292943',
    projectId: 'guardianwatch-b1972',
    storageBucket: 'guardianwatch-b1972.firebasestorage.app',
    androidClientId: '19497292943-mbajhhb8csugrce5hq1mlrhod0i3spob.apps.googleusercontent.com',
    iosClientId: '19497292943-ikdgfap4bl8i7drfukkqork7vi3ohsk9.apps.googleusercontent.com',
    iosBundleId: 'com.circum.guardianwatch',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSD5Dl2CbWvyaY2cZISSwEAouoFNn9bJI',
    appId: '1:19497292943:ios:741b21190bd9b6bbedccfa',
    messagingSenderId: '19497292943',
    projectId: 'guardianwatch-b1972',
    storageBucket: 'guardianwatch-b1972.firebasestorage.app',
    androidClientId: '19497292943-mbajhhb8csugrce5hq1mlrhod0i3spob.apps.googleusercontent.com',
    iosClientId: '19497292943-ikdgfap4bl8i7drfukkqork7vi3ohsk9.apps.googleusercontent.com',
    iosBundleId: 'com.circum.guardianwatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkWhDOmLXmGzWdqegxjMuv3ZDUYmY3spM',
    appId: '1:19497292943:web:96cd1c36d555d523edccfa',
    messagingSenderId: '19497292943',
    projectId: 'guardianwatch-b1972',
    authDomain: 'guardianwatch-b1972.firebaseapp.com',
    storageBucket: 'guardianwatch-b1972.firebasestorage.app',
    measurementId: 'G-8JP9F3FMGP',
  );
}
