"""initial schema

Revision ID: 071ab0e56fa3
Revises: 
Create Date: 2026-08-17 04:09:04.401228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.db_types  # required for the UTCDateTime type used below —
# autogenerate references it but doesn't add the import automatically


# revision identifiers, used by Alembic.
revision: str = '071ab0e56fa3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.String(length=1024), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('premium', sa.Boolean(), nullable=False),
    sa.Column('premium_expires_at', app.utils.db_types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.utils.db_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', app.utils.db_types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('normal', 'caution', 'warning', 'critical', name='insightseverity', native_enum=False, length=16), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('generated_at', app.utils.db_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.utils.db_types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_generated_at'), 'insights', ['generated_at'], unique=False)
    op.create_index(op.f('ix_insights_user_id'), 'insights', ['user_id'], unique=False)
    op.create_table('readings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('spo2', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('ecg_mv', sa.JSON(), nullable=True),
    sa.Column('battery', sa.Integer(), nullable=True),
    sa.Column('recorded_at', app.utils.db_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.utils.db_types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readings_recorded_at'), 'readings', ['recorded_at'], unique=False)
    op.create_index('ix_readings_user_recorded', 'readings', ['user_id', 'recorded_at'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.Enum('ios', 'android', name='iapplatform', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'invalid', 'cancelled', name='subscriptionstatus', native_enum=False, length=16), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('raw_receipt', sa.Text(), nullable=True),
    sa.Column('verified_at', app.utils.db_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.utils.db_types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_readings_user_recorded', table_name='readings')
    op.drop_index(op.f('ix_readings_recorded_at'), table_name='readings')
    op.drop_table('readings')
    op.drop_index(op.f('ix_insights_user_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_generated_at'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
