# Generated by Django 6.0.3 on 2026-05-22 06:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('heart_rate', models.PositiveSmallIntegerField()),
                ('spo2', models.PositiveSmallIntegerField()),
                ('temperature', models.FloatField()),
                ('recorded_at', models.DateTimeField()),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Health Record',
                'verbose_name_plural': 'Health Records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('detail', models.TextField()),
                ('severity', models.CharField(choices=[('normal', 'Normal'), ('caution', 'Caution'), ('warning', 'Warning'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Insight',
                'verbose_name_plural': 'Insights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('displayName', models.CharField(blank=True, max_length=255)),
                ('photoURL', models.URLField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastLoginAt', models.DateTimeField(blank=True, null=True)),
                ('premium', models.BooleanField(default=False)),
                ('premiumExpiry', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'managed': False,
            },
        ),
    ]
